server:
  port: 8080
  
spring:
  application:
    name: api-gateway
  cloud:    gateway:      routes:      - id: review-service
        uri: lb://REVIEW-SERVICE
        predicates:        - Path= /reviews/**
          

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"