server:
  port: 6063

spring:
  application:
    name: hotel-service

  config:
    import: configserver:http://localhost:8888
    
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
      


            

